name: safa_hr
description: "safa.hr webpage"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  domain:
    path: domain
  di:
    path: di

  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  flutter_riverpod: ^2.4.9
  go_router: ^7.0.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  layout: ^1.0.5
  url_launcher: ^6.2.2
  flutter_animated_icons: ^1.0.1
  expandable_menu: ^0.0.5
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  melos: ^3.4.0
  theme_tailor: ^2.0.2
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  go_router_builder: ^2.3.3

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira-VariableFont_wdth,wght.ttf
  assets:
    - assets/images/
    - assets/images/dashboard/

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true